# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Transformation Agency
email: web.team@digital.gov.au
description: > # this means to ignore newlines until "baseurl:"
  Driving the digital transformation of government information and services,
  making them simpler, clearer, faster.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.digital.gov.au" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/:categories/:title/"

uikit_base_url: "https://gov-au-ui-kit.apps.platform.digital.gov.au/latest/"

google_tag_manager: GTM-KR7JDF #TODO this is dto.gov.au

# Because there is no way to instantiate an empty array, and we need to merge two filtered
# collections together -- this is used on the News page layout.
empty-array: []

collections:
  assessment-reports:
    output: true
  projects:
    output: true
  teams:
    output: true
  leadership-group:
    output: true

# Build settings
markdown: kramdown

gems:
  - jekyll-assets
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - bin
  - circle.yml
  - README.md
  - manifest*.yml

assets:
  sources:
    - _assets/scss
    - _assets/vendor
    - _assets/img
  compress:
    css: true
    js: false
  cache: .asset-cache
  prefix: "/"
  digest: true


defaults:
  -
    scope:
      path: "" # empty string means all files
    values:
      layout: "default"

