---
env: development
exclude:
- ".about.yml"
- ".cfignore"
- ".codeclimate.yml"
- ".gitignore"
- ".gitmodules"
- ".hound.yml"
- _styleguide/
- api-endpoints
- bin
- build
- circle.yml
- config_blog.rb
- CONTRIBUTING.md
- docker-compose.yml
- docker_entrypoint.rb
- Dockerfile
- examples/
- favicon.ico
- feed*
- Gemfile*
- humans.txt
- ISSUE_TEMPLATE.md
- killport
- LICENSE.md
- node_modules
- package.json
- pages/our-work.html
- PULL_REQUEST_TEMPLATE.md
- README.md
- robots.txt
- search-index*
- serve
- serve-blog
- serve-fast
- serve-accesslint
- spec/
- system-security-plan.yml
- tags/
- tests/
- tests/schema/tags.yml
- vendor
- pages/standard/*
- pages/blog/*
- pages/news/*
- pages/what-we-do/*
- pages/who-we-are/*
- files*
- _assessment-reports/*
- pages/404.md
---
