---
env: development
exclude:
- ".about.yml"
- ".cfignore"
- ".codeclimate.yml"
- ".gitignore"
- ".gitmodules"
- ".hound.yml"
- _styleguide/
- api-endpoints
- bin
- build
- circle.yml
- config_blog.rb
- CONTRIBUTING.md
- docker-compose.yml
- docker_entrypoint.rb
- Dockerfile
- examples/
- favicon.ico
- feed*
- Gemfile*
- humans.txt
- ISSUE_TEMPLATE.md
- killport
- LICENSE.md
- node_modules
- package.json
- pages/our-work.html
- PULL_REQUEST_TEMPLATE.md
- README.md
- robots.txt
- search-index*
- serve
- serve-blog
- serve-fast
- serve-accesslint
- spec/
- system-security-plan.yml
- tags/
- tests/
- tests/schema/tags.yml
- vendor
- _posts/2015-03-27-dto-launches-at-the-digital-innovation-forum.md
- _posts/2015-04-07-introducing-the-digital-transformation-office.md
- _posts/2015-04-07-release-of-the-alpha-digital-service-standard.md
- _posts/2015-04-22-q-and-as-on-the-digital-service-standard.md
- _posts/2015-04-28-meeting-the-needs-of-different-users.md
- _posts/2015-05-12-the-digital-transformation-agenda-in-the-2015-16-federal-budget.md
- _posts/2015-05-15-putting-the-user-at-the-centre-of-everything.md
- _posts/2015-05-18-digitising-mail.md
- _posts/2015-06-02-building-better-services-with-analytics.md
- _posts/2015-06-16-updates-to-the-scope-of-the-digital-service-standard.md
- _posts/2015-06-19-transforming-government-information.md
- _posts/2015-06-26-iaward-innovators.md
- _posts/2015-07-02-making-government-discoverable.md
- _posts/2015-07-03-hacking-for-better-government-services.md
- _posts/2015-07-10-government-working-with-government-lessons-from-onegov.md
- _posts/2015-07-13-where-are-we-heading-a-future-state-for-user-experience.md
- _posts/2015-07-14-introducing-our-new-ceo-fresh-from-the-uks-government-digital-service-gds.md
- _posts/2015-07-17-david-hazlehurst-to-depart-the-dto.md
- _posts/2015-07-22-talking-digital-id.md
- _posts/2015-07-29-dto-gov-au-gets-the-first-of-many-makeovers.md
- _posts/2015-07-29-its-here-the-digital-service-design-guides-have-arrived-in-alpha.md
- _posts/2015-08-07-preface-to-the-api-design-guide.md
- _posts/2015-08-12-the-dto-now-manage-government-authentication-frameworks.md
- _posts/2015-08-14-open-and-secure.md
- _posts/2015-08-18-your-homepage-is-not-your-front-door.md
- _posts/2015-08-21-getting-inside-your-head-analysing-search-behaviours.md
- _posts/2015-08-21-how-do-australians-really-feel-about-digital-government-services.md
- _posts/2015-08-24-digital-community-of-practice-event-4-september.md
- _posts/2015-08-24-showing-the-thing-was-our-theme-last-week-in-the-standards-team.md
- _posts/2015-08-27-recruitment-campaign-to-find-australias-best-tech-talent.md
- _posts/2015-09-09-digital-community-of-practice-event-14-september.md
- _posts/2015-10-07-service-design-in-government-join-the-community.md
- _posts/2015-10-14-announcing-our-work-programme.md
- _posts/2015-10-16-digital-service-standard-moves-to-beta.md
- _posts/2015-10-21-dto-is-the-incubator-and-government-is-the-start-up.md
- _posts/2015-10-22-were-extending-our-open-door-policy-with-an-open-day-at-the-dtos-sydney-office-next-friday-30-october.md
- _posts/2015-11-02-doing-discovery-in-government.md
- _posts/2015-11-10-what-is-discovery.md
- _posts/2015-11-20-documenting-discovery.md
- _posts/2015-12-04-a-food-analogy-to-understand-user-research.md
- _posts/2015-12-08-Want-to-work-on-stuff-that-matters.md
- _posts/2015-12-14-research-recruitment-on-social-media.md
- _posts/2015-12-15-making-it-easier-for-startups-and-sme-to-help-government.md
- _posts/2015-12-17-gov-au-the-first-9-weeks.md
- _posts/2015-12-24-the-first-alpha-passes-its-service-assessment.md
- _posts/2016-01-05-how-were-tracking-progress-in-our-digital-delivery-hubs.md
- _posts/2016-01-08-new-division-to-drive-digital-transformation.md
- _posts/2016-02-01-event-CSS-inventor-to-visit-the-DTO.md
- _posts/2016-02-03-so-what-does-a-delivery-manager-do.md
- _posts/2016-02-12-gov-au-passes-alpha-assessment.md
- _posts/2016-03-01-event-how-platforms-work.md
- _posts/2016-03-03-another-dt-project-passess-assessment.md
- _posts/2016-03-08-digital-identity-early-days-in-the-discovery-process.md
- _posts/2016-03-10-announcing-the-alpha-guide.md
- _posts/2016-03-16-gov-au-is-a-mental-model-for-government.md
- _posts/2016-03-18-gov-au-is-not-a-technology-project.md
- _posts/2016-03-18-new-panel-to-bring-in-digital-expertise.md
- _posts/2016-03-21-gov-au-content-model-explained.md
- _posts/2016-03-23-gov-au-alpha-prototype-now-public.md
- _posts/2016-03-29-cognitive-bias-in-discovery.md
- _posts/2016-03-31-govau-beta-now-underway.md
- _posts/2016-04-04-gov-au-alpha-prototype-live-event.md
- _posts/2016-04-05-communications-and-arts-joins-gov-au.md
- _posts/2016-04-06-what-do-we-mean-by-digital.md
- _posts/2016-04-11-event-github-for-government.md
- _posts/2016-04-12-wrapping-up-discovery-on-starting-a-business.md
- _posts/2016-04-13-gdsdtomou.md
- _posts/2016-04-19-govcmsandgovaubeta.md
- _posts/2016-04-21-govau-stickynotes.md
- _posts/2016-04-21-in-flight-assessment-model.md
- _posts/2016-04-26-platforms-for-government.md
- _posts/2016-05-03-diversity-of-our-users.md
- _posts/2016-05-04-show-n-tell.md
- _posts/2016-05-05-walking-the-talk.md
- _posts/2016-05-06-standard-goes-live.md
- _posts/2016-07-15-canberra-dto-open-house.md
- _posts/2016-07-20-approach-to-accessibility.md
- _posts/2016-07-27-dto-turns-one.md
- _posts/2016-08-02-new-standard-of-reporting.md
- _posts/2016-08-29-digital-marketplace-beta.md
- _posts/2016-09-06-announcement-peter-alexander.md
- _posts/2016-10-21-marketplace-sharing-positive-feedback.md
- _posts/2016-10-28-new-digital-agency-establishes-agenda.md
- _posts/2016-11-09-marketplace-shaped-by-user-needs.md
- _posts/2016-11-18-marketplace-roundtable.md
- _posts/2016-11-22-how-the-bom-put-users-needs-first.md
- _posts/2016-11-30-paul-shetler-resignation.md
- _posts/2016-12-15-digital-steps-to-benefit-users.md
- _posts/2017-01-13-give-and-take.md
- _posts/2017-01-19-ab-coding.md
- _posts/2017-01-31-early-marketplace-adoption-pays-off.md
- _posts/2017-02-02-dashboard-practising-what-we-preach.md
- _posts/2017-02-02-dashboard-progress.md
- _posts/2017-02-09-creating-good-content.md
---
